### ISSUE TITLE
点击头像 怎么把下面收回去 和滑动的效果一样？

### ISSUE THREAD

**Issue by wang2016215** [wangweiqi23/eleme-master#2]

**Comment by wangweiqi23** [comment]
自己写一个属性动画 调整滑动值

**Comment by wang2016215** [comment]
可以写下吗 大佬

**Comment by wangweiqi23** [comment]
if (mOffsetAnimator == null) {
            mOffsetAnimator = new ValueAnimator();
            mOffsetAnimator.setInterpolator(AnimationUtils.DECELERATE_INTERPOLATOR);
            mOffsetAnimator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
                @Override
                public void onAnimationUpdate(ValueAnimator animator) {
                    //类似于这样的处理呀
                    setHeaderTopBottomOffset(coordinatorLayout, child,
                            (Integer) animator.getAnimatedValue());
                }
            });
        } else {
            mOffsetAnimator.cancel();
        }

        mOffsetAnimator.setDuration(Math.min(duration, MAX_OFFSET_ANIMATION_DURATION));
        mOffsetAnimator.setIntValues(currentOffset, offset);
        mOffsetAnimator.start();

**Comment by wangweiqi23** [comment]
```
if (mOffsetAnimator == null) {
            mOffsetAnimator = new ValueAnimator();
            mOffsetAnimator.setInterpolator(AnimationUtils.DECELERATE_INTERPOLATOR);
            mOffsetAnimator.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
                @Override
                public void onAnimationUpdate(ValueAnimator animator) {
                    setHeaderTopBottomOffset(coordinatorLayout, child,
                            (Integer) animator.getAnimatedValue());
                }
            });
        } else {
            mOffsetAnimator.cancel();
        }

        mOffsetAnimator.setDuration(Math.min(duration, MAX_OFFSET_ANIMATION_DURATION));
        mOffsetAnimator.setIntValues(currentOffset, offset);
        mOffsetAnimator.start();
```
类似于这样  demo里面拉到底点击向上箭头也会收起的

**Comment by wang2016215** [comment]
谢谢，参照点击向上箭头 好像实现了

**Comment by wangweiqi23** [comment]
😀 能帮到大家就好
