### ISSUE TITLE
在评论里面的fragment里面有一个RecyclerView列表怎么使他可以滑动

### ISSUE THREAD

**Issue by wang2016215** [wangweiqi23/eleme-master#4]

**Comment by wangweiqi23** [comment]
对应fragment里面设置禁止嵌套滑动的 你可以按需求改下代码

**Comment by wang2016215** [comment]
如果要动态设置详情里面的数据 是不是要加载网络请求后才初始化  initAppBar(); 不然里面的高度问题引起很多显示不全

**Comment by wangweiqi23** [comment]
嗯 这个参考的饿了么 他们也是先计算再显示的

**Comment by wang2016215** [comment]
![_20180704103706](https://user-images.githubusercontent.com/19322441/42253833-3a41f284-7f76-11e8-8e93-0e0c55eaa399.jpg)


大佬最后一个问题 就是滑动的时候 和点击添加购物车的时候会出现这个白条，遮挡住了tab 这个有遇到过吗 ，在列表里的加号点击 执行   notifyDataSetChanged(); 就会出现。能给个思路么 谢谢

**Comment by wangweiqi23** [comment]
可能是某一层背景色问题 你检查你的代码

**Comment by wang2016215** [comment]
我在你的demo 里面试了下 也出现，，

**Comment by wangweiqi23** [comment]
啊 我晚上看一下

**Comment by wangweiqi23** [comment]
这个问题 我修复了  你拉一下最新代码

**Comment by wang2016215** [comment]
好的谢谢了
